{
  "parameter(s)": [
    29,
    53,
    42
  ],
  "test_result_is_divisible_by_numbers": [
    "failed",
    "UnboundLocalError: cannot access local variable 'y' where it is not associated with a value",
    0.00012
  ],
  "test_list_of_ones": [
    "failed",
    "ValueError: max() iterable argument is empty",
    0.00019
  ],
  "test_list_of_prime_numbers": [
    "failed",
    "UnboundLocalError: cannot access local variable 'y' where it is not associated with a value",
    0.00018
  ]
}