{
  "parameter(s)": [
    40
  ],
  "test_horizontal_matrix": [
    "failed",
    "numpy.exceptions.AxisError: axis 2 is out of bounds for array of dimension 2",
    0.00027
  ],
  "test_matrix_of_having_40_integers": [
    "failed",
    "numpy.exceptions.AxisError: axis 2 is out of bounds for array of dimension 2",
    0.00032
  ],
  "test_matrix_of_one_integer": [
    "failed",
    "numpy.exceptions.AxisError: axis 2 is out of bounds for array of dimension 2",
    0.00023
  ]
}