{
  "parameter(s)": [
    [
      86,
      77
    ],
    48
  ],
  "test_index_of_inserted_element": [
    "failed",
    "numpy.exceptions.AxisError: axis 1 is out of bounds for array of dimension 1",
    0.00018
  ],
  "test_presence_of_inserted_element_at_index_48": [
    "failed",
    "numpy.exceptions.AxisError: axis 1 is out of bounds for array of dimension 1",
    0.00017
  ],
  "test_presence_of_inserted_element": [
    "failed",
    "numpy.exceptions.AxisError: axis 1 is out of bounds for array of dimension 1",
    0.00019
  ]
}